-- try something
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;

-- CHANGE TO THAT ONE
USE hbtn_0d_usa;

-- NEW TABLE
CREATE TABLE IF NOT EXISTS cities (
	id 	INT 	NOT NULL AUTO_INCREMENT PRIMARY KEY,
       	state_id INT 	NOT NULL,
	name 	VARCHAR(256) NOT NULL,
	FOREIGN KEY (state_id) REFERENCES states(id)
);
